require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1'
install! 'cocoapods', :deterministic_uuids => false

ENV['NODE_BINARY'] = `which node`.strip
ENV['RCT_NEW_ARCH_ENABLED'] = '0'
ENV['NO_FLIPPER'] = '1'

target 'questionnaire' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

#   pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'questionnaireTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!({ 'Flipper' => '0.78.0' })

  # post_install do |installer|
  #   react_native_post_install(installer)
  #   __apply_Xcode_12_5_M1_post_install_workaround(installer)
  # end

  # Добавляем настройки конфигурации pre_install
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end

  post_install do |installer|
    react_native_post_install(installer)
    
    # Добавляем настройки, которые помогут избежать проблем с линковкой
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        
        # Для решения проблем с ARM64 архитектурой
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = ""
        
        # Добавляем настройки Swift
        config.build_settings['SWIFT_VERSION'] = '5.0'
        
        # Исправляем проблему с инициализацией библиотек C++
        config.build_settings['OTHER_LDFLAGS'] ||= ''
        config.build_settings['OTHER_LDFLAGS'] += ' -ObjC -lc++'
        
        # Битовая глубина
        if config.name == 'Debug'
          config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
        elsif config.name == 'Release'
          config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
          config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
        end
      end
      
      # Отключаем проверки валидаций, которые могут вызывать проблемы
      if target.name == 'React-Core'
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_FABRIC_ENABLED=0'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_NEW_ARCH_ENABLED=0'
        end
      end
    end
  end
end
